version: '3'

#networks:
#  dbnetwork:
#    driver: bridge


services:
  postgres:
    image: postgres
    container_name: db-pg16-file
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "090821"
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#    restart: always
#    networks:
#      - dbnetwork
#  app:
#    build: .
#    image: authmodule
#    container_name: auth-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    networks:
#      - dbnetwork

#  db:
#    ports:
#      - "5432:5432"
#    container_name: postgres_container
#    image: postgres
#    environment:
#
#        POSTGRES_USER: "postgres"
#        POSTGRES_PASSWORD: "090821"
#
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#    restart: always
#    networks:
#      - dbnetwork

#  backend:
#    build: .
#    container_name: spring_container
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/auth"
#      SPRING_DATASOURCE_USERNAME: "postgres"
#      SPRING_DATASOURCE_PASSWORD: "090821"
#      SERVICE_TAGS: test
#    depends_on:
#      - db
#    restart: always
#networks:
#    dbnetwork:
#      driver: bridge

