version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "090821"

    ports:
     - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
        - local-postgres-compose-network

networks:
    local-postgres-compose-network:
        driver: bridge
