INSERT INTO users (id, login, password, email, name, unidade, creationDate, role)
VALUES
    ('1', 'joao.silva', 'senha123', 'joao.silva@example.com', 'João Silva', 'Unidade 1', now(), 'USER'),
    ('2', 'maria.santos', '456abc', 'maria.santos@example.com', 'Maria Santos', 'Unidade 2', now(), 'USER'),
    ('3', 'pedro.oliveira', 'mySecurePassword', 'pedro.oliveira@example.com', 'Pedro Oliveira', 'Unidade 3', now(), 'USER'),
    ('4', 'ana.pereira', 'p@ssw0rd', 'ana.pereira@example.com', 'Ana Pereira', 'Unidade 4', now(), 'USER'),
    ('5', 'carlos.souza', 'strongPass123', 'carlos.souza@example.com', 'Carlos Souza', 'Unidade 5', now(), 'USER'),
    ('6', 'laura.rodrigues', 'safePass!23', 'laura.rodrigues@example.com', 'Laura Rodrigues', 'Unidade 6', now(), 'USER'),
    ('7', 'andre.almeida', 'securePwd2023', 'andre.almeida@example.com', 'André Almeida', 'Unidade 7', now(), 'USER'),
    ('8', 'sofia.martins', 'password123', 'sofia.martins@example.com', 'Sofia Martins', 'Unidade 8', now(), 'USER'),
    ('9', 'lucas.ferreira', '12345678', 'lucas.ferreira@example.com', 'Lucas Ferreira', 'Unidade 9', now(), 'USER'),
    ('10', 'carolina.gomes', 'secretPass', 'carolina.gomes@example.com', 'Carolina Gomes', 'Unidade 10', now(), 'USER'),
    ('11', 'marcos.carvalho', 'mySecret123', 'marcos.carvalho@example.com', 'Marcos Carvalho', 'Unidade 11', now(), 'USER'),
    ('12', 'juliana.vieira', 'superSecurePwd', 'juliana.vieira@example.com', 'Juliana Vieira', 'Unidade 12', now(), 'USER'),
    ('13', 'rafael.pereira', 'pass12345', 'rafael.pereira@example.com', 'Rafael Pereira', 'Unidade 13', now(), 'USER'),
    ('14', 'camila.santos', 'safePassword', 'camila.santos@example.com', 'Camila Santos', 'Unidade 14', now(), 'USER'),
    ('15', 'gustavo.lima', 'securePass123', 'gustavo.lima@example.com', 'Gustavo Lima', 'Unidade 15', now(), 'USER'),
    ('16', 'isabela.fernandes', 'abcdefg', 'isabela.fernandes@example.com', 'Isabela Fernandes', 'Unidade 16', now(), 'USER'),
    ('17', 'luiz.goncalves', 'qwerty', 'luiz.goncalves@example.com', 'Luiz Gonçalves', 'Unidade 17', now(), 'USER'),
    ('18', 'mariana.rodrigues', '1234abcd', 'mariana.rodrigues@example.com', 'Mariana Rodrigues', 'Unidade 18', now(), 'USER'),
    ('19', 'bruno.ferreira', 'passpass', 'bruno.ferreira@example.com', 'Bruno Ferreira', 'Unidade 19', now(), 'USER'),
    ('20', 'leticia.silva', 'ilovecoding', 'leticia.silva@example.com', 'Letícia Silva', 'Unidade 20', now(), 'ADMIN');
